version: "3"
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subquery
    volumes:
      - postgres-data:/var/lib/postgresql/data

  indexer:
    depends_on:
      - postgres
    image: subquerynetwork/node-ethereum:latest
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: subquery
    volumes:
      - ./:/app
      - /app/node_modules
    command: -f /app

  query:
    depends_on:
      - indexer
    image: subquerynetwork/query:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: subquery

volumes:
  postgres-data:
