/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ArenaInterface extends utils.Interface {
  functions: {
    "combatInProgress()": FunctionFragment;
    "combatResultNFT()": FunctionFragment;
    "fighter1()": FunctionFragment;
    "fighter2()": FunctionFragment;
    "owner()": FunctionFragment;
    "register(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "resolveCombat()": FunctionFragment;
    "totalCombats()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "yokiNFT()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "combatInProgress"
      | "combatResultNFT"
      | "fighter1"
      | "fighter2"
      | "owner"
      | "register"
      | "renounceOwnership"
      | "resolveCombat"
      | "totalCombats"
      | "transferOwnership"
      | "yokiNFT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "combatInProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "combatResultNFT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fighter1", values?: undefined): string;
  encodeFunctionData(functionFragment: "fighter2", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveCombat",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCombats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "yokiNFT", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "combatInProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "combatResultNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fighter1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fighter2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveCombat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCombats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yokiNFT", data: BytesLike): Result;

  events: {
    "CombatResolved(uint256,uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "YokiRegistered(address,uint256,uint8,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CombatResolved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "YokiRegistered"): EventFragment;
}

export interface CombatResolvedEventObject {
  winnerTokenId: BigNumber;
  loserTokenId: BigNumber;
  winner: string;
  loser: string;
  winnerScore: BigNumber;
  loserScore: BigNumber;
  combatResultTokenId: BigNumber;
}
export type CombatResolvedEvent = TypedEvent<
  [BigNumber, BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  CombatResolvedEventObject
>;

export type CombatResolvedEventFilter = TypedEventFilter<CombatResolvedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface YokiRegisteredEventObject {
  owner: string;
  tokenId: BigNumber;
  slotIndex: number;
  totalScore: BigNumber;
}
export type YokiRegisteredEvent = TypedEvent<
  [string, BigNumber, number, BigNumber],
  YokiRegisteredEventObject
>;

export type YokiRegisteredEventFilter = TypedEventFilter<YokiRegisteredEvent>;

export interface Arena extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArenaInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    combatInProgress(overrides?: CallOverrides): Promise<[boolean]>;

    combatResultNFT(overrides?: CallOverrides): Promise<[string]>;

    fighter1(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        tokenId: BigNumber;
        totalScore: BigNumber;
      }
    >;

    fighter2(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        tokenId: BigNumber;
        totalScore: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    register(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    resolveCombat(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    totalCombats(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    yokiNFT(overrides?: CallOverrides): Promise<[string]>;
  };

  combatInProgress(overrides?: CallOverrides): Promise<boolean>;

  combatResultNFT(overrides?: CallOverrides): Promise<string>;

  fighter1(
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      owner: string;
      tokenId: BigNumber;
      totalScore: BigNumber;
    }
  >;

  fighter2(
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      owner: string;
      tokenId: BigNumber;
      totalScore: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  register(
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  resolveCombat(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  totalCombats(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  yokiNFT(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    combatInProgress(overrides?: CallOverrides): Promise<boolean>;

    combatResultNFT(overrides?: CallOverrides): Promise<string>;

    fighter1(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        tokenId: BigNumber;
        totalScore: BigNumber;
      }
    >;

    fighter2(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        tokenId: BigNumber;
        totalScore: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    register(tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    resolveCombat(overrides?: CallOverrides): Promise<void>;

    totalCombats(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    yokiNFT(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CombatResolved(uint256,uint256,address,address,uint256,uint256,uint256)"(
      winnerTokenId?: BigNumberish | null,
      loserTokenId?: BigNumberish | null,
      winner?: string | null,
      loser?: null,
      winnerScore?: null,
      loserScore?: null,
      combatResultTokenId?: null
    ): CombatResolvedEventFilter;
    CombatResolved(
      winnerTokenId?: BigNumberish | null,
      loserTokenId?: BigNumberish | null,
      winner?: string | null,
      loser?: null,
      winnerScore?: null,
      loserScore?: null,
      combatResultTokenId?: null
    ): CombatResolvedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "YokiRegistered(address,uint256,uint8,uint256)"(
      owner?: string | null,
      tokenId?: BigNumberish | null,
      slotIndex?: null,
      totalScore?: null
    ): YokiRegisteredEventFilter;
    YokiRegistered(
      owner?: string | null,
      tokenId?: BigNumberish | null,
      slotIndex?: null,
      totalScore?: null
    ): YokiRegisteredEventFilter;
  };

  estimateGas: {
    combatInProgress(overrides?: CallOverrides): Promise<BigNumber>;

    combatResultNFT(overrides?: CallOverrides): Promise<BigNumber>;

    fighter1(overrides?: CallOverrides): Promise<BigNumber>;

    fighter2(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    register(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    resolveCombat(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    totalCombats(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    yokiNFT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    combatInProgress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    combatResultNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fighter1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fighter2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    register(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    resolveCombat(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    totalCombats(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    yokiNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
